name: Test Hysteria2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"
  push:
    paths:
      - 'subs/type/hysteria2/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install "httpx[socks]" socksio uvloop

      - name: Download latest sing-box
        run: |
          echo "🔍 Получаем самую новую версию sing-box..."
          TAG=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)
          echo "Последняя версия: $TAG"

          FILE="sing-box-${TAG#v}-linux-amd64.tar.gz"
          URL="https://github.com/SagerNet/sing-box/releases/download/${TAG}/${FILE}"

          echo "🧹 Удаляем старые версии..."
          rm -rf sing-box-* || true

          echo "⬇️ Скачиваем: $URL"
          wget -q "$URL" -O sing-box.tar.gz

          echo "📦 Распаковываем..."
          tar -xzf sing-box.tar.gz

          FOLDER=$(ls -d sing-box-*/ | head -n 1 | tr -d '/')
          echo "📁 Найдена папка: $FOLDER"

          chmod +x "$FOLDER/sing-box"
          sudo cp "$FOLDER/sing-box" /usr/local/bin/

          echo "🔧 Проверяем версию:"
          sing-box version

      - name: Run Hysteria2 Tester
        run: python tester.py

      - name: Commit and push results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tested/
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Auto test Hysteria2 - $(date +'%Y-%m-%d %H:%M UTC')"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}